// Package weather provides ...
package weather

// CurrentCondition represents ...
var CurrentCondition string
// CurrentLocation ...
var CurrentLocation string

// Forecast ...
func Forecast(city, condition string) string {
	CurrentLocation, CurrentCondition = city, condition
	return CurrentLocation + " - current weather condition: " + CurrentCondition
}
